apiVersion: v1
data:
  RAILS_ENV: {{ .Values.diaspora_environment.rails_env }}
kind: ConfigMap
metadata:
  labels:
    app: {{ template "diaspora.name" . }}
    chart: {{ template "diaspora.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ template "diaspora.fullname" . }}
