apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "diaspora.fullname" . }}
  labels:
    app: {{ template "diaspora.name" . }}
    chart: {{ template "diaspora.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "diaspora.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "diaspora.name" . }}
        release: {{ .Release.Name }}
    spec:
      volumes:
        - name: diaspora-config-volume
          configMap:
            name: configtest
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: [ "tail", "-f", "/dev/null" ]
          envFrom:
          - configMapRef:
              name: {{ template "diaspora.fullname" . }}
          env:
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: password
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: diaspora-config-volume
              mountPath: /home/diaspora/kube-configs
          #livenessProbe:
          #  httpGet:
          #    path: /
          #    port: http
          #readinessProbe:
          #  httpGet:
          #    path: /
          #    port: http
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
