apiVersion: v1
kind: Secret
metadata:
  name: postgres
type: Opaque
data:
  password: {{ b64enc .Values.postgresql.postgresPassword }}

---

apiVersion: v1
kind: Secret
metadata:
  name: redis
type: Opaque
data:
  password: {{ b64enc .Values.redis.redisPassword }}
